### ISSUE TITLE
Support arbitrary names in TDMorph COMP preset Buttons

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#102]
The PresetComposer let us rename the presets in the left side panel even when using it with the TDMorph main COMP but doing so will make it impossible to store values to this preset unless the user knows their way around the /TDMorph/Container1/PanelContent/ElementsContainer/PresetManager COMP.

I understand what's going on but this reveals another issue that will remains until something is changed. Not being able to use the main comp with custom names even though the presetManager supports them will always create this type of issue.

I agree with your position on not displaying custom names in the main comp but maybe those buttons could display the index but still support a label or alias system.

**Comment by DarienBrito** [comment]
Find a way to check for proper keys instead of relying on buttons indexes...

**Comment by DarienBrito** [comment]
This was one hell of a problem but it is now solved in (I believe) the most elegant way possible, given TDMorph's architecture. Managed to solved lots of re-ordering, re-naming and dependency calls that must happen when combining internal and external UI's, in just 13 lines of code without changing any of the simplicity of the preset buttons inner workings ;)
