### ISSUE TITLE
PresetComposer, minor bug. Blending initial deck values (blend from and blend to) do not work.

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#104]
Upon creation, the PresetComposer Blending parameter is disabled but it still has two presets set by default for Blend From and Blend To (I call those decks, as if this was a dj crossfader).

By default, both decks are set to 2. After enabling blending and even after setting a different preset to deck A, the crossfader won't work until you manually assign a preset to both decks.

edit: blending in the main comp works fine.

**Comment by DarienBrito** [comment]
This got solved by fixing #103
