### ISSUE TITLE
Feature: midi / osc mapping for Blending

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#105]

**Comment by DarienBrito** [comment]
MIDI and OSC mapping for the PresetComposer will be added later, with the same learning mechanism that the main TDmorph has.

I am still not 100% sure I want to keep blending in the PresetComposer. Don't know if its that handy in there. Thoughts?

Anyways, I'm closing this specific issue and creating a new issue for general MIDI in the preset composer.

**Comment by johannbl** [comment]
Blending can be a performing tool. In this sense, maybe it fits in the preset composer.

However, I find it mostly useful when manually performing with presets and parameters. In that sense, it's not meant to be tied to the presetComposer, which automates thing.

Another key feature of blending presets is to manually find sweet spots that can be saved as alternate versions of the presets you already have. Because you can't store presets directly from the PresetComposer, I think it might be out of place.

I know you don't depend on the main comp to use the presetComposer but I think they make a great pair. In such case you have the same feature at two different locations and yet they aren't connected. I think it could be great to have a standalone Blending module. I intend to update my simple XYpad to work with 2.0 with the PresetGrabber, that could cover it.
