### ISSUE TITLE
PresetAnimator doesn't use the correct morph time value for each parameters.

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#110]
The transition between Preset 1 and Preset 2 will use the set morph time from Preset 1 instead of the value stored with Preset 2.

Preset 1's morph time should only be used when morphing TO Preset 1, not FROM Preset 1. Within the PresetAnimator, you never travel TO Preset 1 so that morph time value should never be used.

The first transition in the Animation should be from Preset 1 to Preset 2. So it should used the morph time stored along with Preset 2.

**Comment by DarienBrito** [comment]
Mmm, strange. I remember doing it like that already... maybe I saved that in the wrong branch :P Anyways, I've corrected, now doing what it should :)
