### ISSUE TITLE
PresetComposer: listing more than one target makes the scene pick one target at random.

### ISSUE THREAD

**Issue by baronlanteigne** [DarienBrito/TDMorph#111]
We discussed this previously. I just forgot to post it here.

The idea is to let users manually write down more than one valid target preset for a scene. Doing so forces the scene to pick one of those preset at random as the target. This behaves similarly to the Pseq, Prand or Pxrand functions from the sequence mode for each parameter.

**Comment by DarienBrito** [comment]
This one will be considered later, not for first release

**Comment by DarienBrito** [comment]
After all this years I'm coming back to this request. I decided that it adds too much complexity to the UI and too many non-trivial changes. Aleatoric selection can be easily tackled with SceneLauncher scripting capability in TDMorph 3.1.0 (coming out very soon)
