### ISSUE TITLE
PresetComposer Scene Length in bars or beats

### ISSUE THREAD

**Issue by ruigato** [DarienBrito/TDMorph#115]
would be really nice to have the option to set the length of the scenes in PresetComposer by bars or beats, besides seconds. Thats mostly because when we use PresetAnimator it will take the length for the keyframe distribution

**Comment by DarienBrito** [comment]
Very interesting one. Considered at length how to offer this and have deviced a method that works with a "Unit" column that gets revealed whenever you choose beat or bar. This unit is a convertor, so if your bpm is 120 and you select "beats" as unit, you may enter 1 in the unit column and the resulting time will be 0.5. These two values are shown to the user so you can always override the conversion by using directy length. 

In a nuthsell: Length always specifies time in seconds, on beat bear, "Unit" allows you to set time as beats or bars.

![Capture](https://user-images.githubusercontent.com/5923038/83681284-7b6aa500-a5e2-11ea-9a43-7d92faa203ad.PNG)
