### ISSUE TITLE
White list par scope option

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#119]
Not sure how to explain this one, its almost like an opposite of locking a parameter. Basically, it would be nice to 'solo' a few parameters, and create a preset that will only affect those targeted parameters. This would allow things like color, camera, lights etc. to have presets that are unique to themselves, while the other parameters are unaffected. 

I know you could make a second slider container to do something like that, but there are plenty or use cases where you might want to recall everything dynamically, or only a subset of parameters. It could be done by locking parameters before storing a preset, and on recall those presets become locked during the interpolation, and go back to normal after the morphtimer is off. Let me know if this makes any sense

**Comment by DarienBrito** [comment]
This is mixing two different behaviours that do kind of the same thing but in opposite ways (locking/soloing) I do not want to clog the UI any more with additional options and I don't feel the benefits of this justify an implementation and adding control for this. Won't do this one.

**Comment by drmbt** [comment]
I would argue that Solo is a significantly more useful function then locking, as it encourages things like morphing multidimensional parameters like transformation, rotation, color etc. more easily. I feel like for both parametric exploration and performance, there are many more situations in which you would want to morph a small group of parameters via solo then there are situations in which its desirable to morph every par except for the lock list. 

I know it means reworking your approach in a few areas, but I'd ask you to consider it if you aren't committed 100% to locking as is, as I do think its much more useful to solo then to lock

**Comment by DarienBrito** [comment]
Solo and locking is the same thing, but from two different angles. I don't see the use of changing this since what you want is just locking every other thing you don't need. There's no difference at all in doing one or the other. Also, presets will never remember locking or soloing because presets need to work in every other TDMorph tool seamlessly and locking brakes that if stored in memory.
