### ISSUE TITLE
Optimize the whole Widget system 

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#126]
TouchDesigner widgets are really bloated and use very inefficient methods, such as getattr all over the place. All Widgets in TDmorph need to be optimized so that they are as efficient as possible.

**Comment by DarienBrito** [comment]
TDMorphButton, TDMorphFloat and TDMorphInt implemented. These greatly reduce the amount of unnecessary code and major inefficiencies in TD Widgets, as well as providing access to the newly implemented universal MIDI and OSC systems. Left to do other types, although optimization seems less urgent given that items of that sort do not ever cook continuously...

**Comment by DarienBrito** [comment]
All Widgets have been optimized and consume now as little memory as possible since each has dedicated tasks with tons of new functionality for mapping MIDI and OSC.

**Comment by DarienBrito** [comment]
Woops, still 2 items to go! Triggers and popus

**Comment by DarienBrito** [comment]
Done

**Comment by drmbt** [comment]
One thing I noticed about the new exec buttons that replaced yFx button is that the scripts no longer execute from the level of the button itself, but now require '../' to go up a level. Certainly a minor thing, but I thought it was a nice touch to think of the execute as the button. may not be worth updating, but thought it was worth mentioning

**Comment by DarienBrito** [comment]
Yes. This was changed because of consistency within TDMorph's widget system. The older behaviour (which is the one you describe) was to execute on the Widget's parent level, so it looks as if you are on the level of the button itself, but that is not true, you were in fact on the parent's level looking at its children. Writing "me" in an expression of a Widget should always refer to the Widget, not to the parent element. So no, will not revert this because is inconsistent.
