### ISSUE TITLE
Revise reference system so paths can be dynamic

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#132]
The very best way to achieve this would be a TouchDesigner assigned consistent UUID over projects. Just like the op(‘node’).id but consistent and persistent. An RFE has been sent to TouchDesigner about this. I rather wait for that that taking other more brute-force aproaches. See this discussion on the forum to refresh memory:

https://forum.derivative.ca/t/dynamic-paths-for-nodes-referencing/137361/6

**Comment by ruigato** [comment]
Hello Darien,

not sure if this it the same issue, but right now when we change the paths feeding the preset manager , the presets stored previously don't work anymore. Is this related to that?

![](http://www.ruigato.info/blog/wp-content/uploads/2021/05/Screenshot-2021-05-28-180410.jpg)

cheers,

**Comment by DarienBrito** [comment]
Hi Rui! No, this one refers to something else. I am creating a new issue for yours ;)

**Comment by DarienBrito** [comment]
Paths are now dynamic in TDMorph3!
