### ISSUE TITLE
blending mode engage

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#137]
I find the current behavior of blending being disabled on execution of a preset to be a bit cumbersome. I've found myself using the xyslider for blending anyhow, but I think the built in functionality would benefit from something that snaps the value on movement of the blend fader as opposed to making them discrete movements, although preferable to jumping entirely would be an arbitrary blend from where the current parameters are. Is that doable, with the blend targets being looked up against the current settings, or does that get too convoluted?

**Comment by DarienBrito** [comment]
No, blending is a very specific and unimportant convenience tool that should only be executed when a user specifically needs to. It is absolutely not a priority in the system. The priority is that morphing is as efficient as possible and warrantied to run when it needs to at all times. That is why they are exclusive. This will not be implemented.
