### ISSUE TITLE
beta 2.4 UIElements break on save and reopen

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#138]
This is pretty simple to produce: TDMorph, add a couple of Noise parameters, save your session, reopen your session. 

Something weird happening on init with the clones would be my guess. Deleting that container also breaks.

**Comment by DarienBrito** [comment]
WTF, this is a really annoying one... Issue is that extensions are not being copied. Same TouchDesigner bug as there was when renaming TDMorph to something else #42

**Comment by DarienBrito** [comment]
Fixed by creating clone inmune elements in the ElementsContainer. See PrivateBeta4.3 in Slack and keep testing please.
