### ISSUE TITLE
TouchDesigner latest build bug: pop() for deeply dependable dictionaries

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#142]
What to do? Wait for them to fix this or put ugly try/catches where needed? 😞

**Comment by DarienBrito** [comment]
Has been reported to TouchDesigner. Ivan has sent the following patch:

> If you unzip these files into the folder with your .toe, the problem will be fixed. This bug will be gone in the next release.

[https://forum.derivative.ca/t/delitem-method-for-dependable-dictionaries-is-broken-in-latest-official-version-may-affect-storage-and-dependable-properties-24520-download-patch-here/140562/3](url)

**Comment by drmbt** [comment]
Hopefully a new stable with some patches drops soon, this last one seems a little buggy in a few spots. I guess worst case you can drop it with the patch and just caveat that they'll need to drop it in the session folder at first...

**Comment by DarienBrito** [comment]
Nah, definitely will wait till they fix the official release before releasing TDMorph.
