### ISSUE TITLE
A way to "purge" differences between the dynamic UI and the static preset file

### ISSUE THREAD

**Issue by markijzerman** [DarienBrito/TDMorph#151]
In the recent version (TDMorph private beta 4.6) when you delete a parameter from a preset and then export, the preset that is exported still has the deleted parameter in there. 

Before exporting, there should be a way to "purge" the discrepancies between the UI and the preset storage, so the exported preset does not carry old parameters- so it should "clean up the store boxed from what is not there anymore, so that it will have the correct data next time you export".

**Comment by DarienBrito** [comment]
Latest version (3.1.0) has a pretty robust mechanism to purge all sort of spurious data that may come along. Releasing it very soon :)
