### ISSUE TITLE
rfe: method for setting arbitrary values in PresetMorpher extension

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#155]
As illustrated through the ParMorph component shared on Slack, a method for setting arbitrary target values for PresetMorpher opens up more options for further extending the module's functionality. Coupled with a method for calling the default value of a parameter and setting that as a target, and the ui.rolloverPar method, morph and randomize could be globally accessible.

This could be cool as a basic functionality of TDMorph, perhaps accessible from the KeysMapper callbacks, but I would probably personally prefer to work with it headlessly added from the tools menu like a PresetManager so that it could exist without a TDMorph instance in a project

**Comment by DarienBrito** [comment]
Things evolved in a certain direction in 3.1.0, closing it as I think some of things address here all covered in upcoming release
