### ISSUE TITLE
experimental 41040 breaks a few things

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#156]
I'd imagine you have no reason to develop for an unstable build, but it may be worth knowing that in the 41040 build, storing presets results in an error popup "There are no associated parameters to make presets from", and global Jump and Morph have no effect. 

The preset manager tox is pretty busted too, nothing is stored. Would be interesting to see why that's happening, in case Derivative is planning on pushing some changes that are catastrophic, figured I'd give you a heads up

**Comment by DarienBrito** [comment]
Ah thanks for the heads up! Certainly hope there's not gonna be the need for massive rewriting! Will have a look :)

**Comment by DarienBrito** [comment]
Solved in latest
