### ISSUE TITLE
rfe: argument for passing range arguments for random morph or MorphGivenParameters methods

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#157]
Pretty self explanatory... I'd like to Morph some built in parameters that by default have a range of 0-1. I'd like to be able to use python to call a morph function, and pass arbitrary values to that method. I suppose I could add a custom parameter with the range that I want, and reference that, but this seems cleaner and more versatile if I know the range I want it to fall in. Let me know if there is a better way I should be thinking of this, or if perhaps adding an option to set a range is a reasonable request

**Comment by DarienBrito** [comment]
Ranges will be restricted to visible controls in the ParameterMorpher module.
