### ISSUE TITLE
Not compatible with dropdown menu widget with changing amount of entries

### ISSUE THREAD

**Issue by markijzerman** [DarienBrito/TDMorph#159]
Hi, I often put the Value0 of different widgets in TDMorph- and often it works fine.
With the dropdown menu however, it only works with the initial set of entries that are in the dropdown menu when I drag it onto TDMorph. When I then add values to the dropdown list, TDMorph can not load or save them. I tried setting the max value of the range to something higher in TDMorph, but this does not seem to work.

In the screenshot, 'G' is added:

![image](https://user-images.githubusercontent.com/2458397/95428271-17b60700-0949-11eb-9256-1077b9845c18.png)

**Comment by DarienBrito** [comment]
Mmm, interesting... I think is because menu's have a special status in TDMorph since they gave me trouble when I was binding them, so they don't update if you add new entries. I will have a look for the first update for V2 ;)

**Comment by DarienBrito** [comment]
This has been completely refactored.
