### ISSUE TITLE
Missing icons on Mac seem to cause buttons not work

### ISSUE THREAD

**Issue by asjer** [DarienBrito/TDMorph#161]
Just tried TDMorph (first time) on my Mac **build 2020.27390 macOS 10.15.7** and some buttons look different and aren't working like are supposed to.

![Screenshot 2020-11-23 at 20 24 04](https://user-images.githubusercontent.com/861966/100006565-f6ab5780-2dca-11eb-90d3-876cfb41b367.gif)

**Comment by DarienBrito** [comment]
In latest version all icons are Material Design, which should work both in Mac and Windows
