### ISSUE TITLE
Preset triggers don't auto populate properly on start with more then 8 presets stored

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#162]
title says it all; as buttons aren't replicated, a cook from changing the number of preset slots is necessary before presets > 8 are properly loaded or displayed in the preset bar on project start. can easily be recreated by storing a 9th preset, saving your project and reloading it. Would be nice if there were some kind of on start check for the number of presets stored that loads them all correctly

**Comment by DarienBrito** [comment]
Solved in latest version
