### ISSUE TITLE
naming issue in 2021 TD stable

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#168]
from a new session, adding a TDmorph tox from github pull and a noise, dragging new paramaters seems to function properly, but labels are all set to None. This may be an issue with something broken in the legacy drag/drop system in 2021; I'd imagine the proper fix might entail refactoring with the new drag/drop callbacks system implemented. figured it was worth a heads up

**Comment by DarienBrito** [comment]
Ah yes, good one. Hopefully I'll have time to do a sweep over all things pending coming month. So this will be fixed in 2.0.1

**Comment by narco** [comment]
Same problem for me on td 12380.
Wich td version is the last working version? 
I can't wait to put my head into it.
Thanks for your amazing job.

**Comment by DarienBrito** [comment]
Fixed in TDMorph3
