### ISSUE TITLE
file may be truncated

### ISSUE THREAD

**Issue by delray** [DarienBrito/TDMorph#175]
Not sure if this is an issue with TD / TDMorph, but I am getting a "Error Loading Network" "File may be Truncated" load error, and the the path is refers to is : _projectname_/TDMorph/Lib/Elements/MenuUI1/element/button/popMenu/.

any pointers?  Eventually the project loads, but then I am missing a TDAbleton component and no perform window comp either. Some backups show the TDMorphUI, others do not.

I have noticed unusually long load times and since playing around with TDMorph the project grew from 1079KB to 4469KB which seems like allot, but maybe that makes sense...
I'm using TDMorph 2.0.0 (with the fix applied to adjust for the 'None' naming), TD 099 2021.14360, Win 10
Happy to help try and track this down together...I'm also going to post on the TD forum

**Comment by DarienBrito** [comment]
Hi there! Thank you for the report. As TD releases new updates, issues like this may appear. There's already some little issues that came with new updates which I haven't had time to fix yet in new versions. 

The issue sounds as if the external dependency of the popMenu is corrupted. I'm extremely busy at the moment so cannot immediately have a look, but I will try to look into it on the weekend. Are you based in Europe by any chance? If so we could chat more or less in real time to sort it out, of course if you feel like it :)

**Comment by DarienBrito** [comment]
Hi @delray Wanted to give you a heads up until I update TDMorph. In order to reduce your file size you can make the TDMorph component external, as in a External .tox. This will keep your original project file size ;)

**Comment by DarienBrito** [comment]
File size greatly reduced in TDMorph3. Should be lighter, faster and nicer :)
