### ISSUE TITLE
References Crash

### ISSUE THREAD

**Issue by pedrofx** [DarienBrito/TDMorph#178]
When I export to TOX and open it in other project or when I copy the scene in other place the references to TDMORPH crashed, it dissapears and I need to make all references.

Thanks.

**Comment by DarienBrito** [comment]
Yes, there's a problem with absolute paths. Is not possible to have fully flexible path addressing in TD, so I have to come up with a better way to do that. Next release of TDMorph will have a better mechanism to handle this,

**Comment by DarienBrito** [comment]
Paths are now flexible in TDMorph3. Possible to re-arrange networks using the PresetManager. Parameter Morpher will soon allow for that too.
