### ISSUE TITLE
MIDI and OSC mapping function broken

### ISSUE THREAD

**Issue by jaaaamIron** [DarienBrito/TDMorph#180]
Hi - running in TD 2021 I've found the MIDI and osc mapping functions don't work. Specifically, when following the mapping process laid out in tutorial 6, the MIDI and osc buttons never begin flashing despite following the process as described.

Is this a known bug, and is there a workaround?

**Comment by DarienBrito** [comment]
Hi. Not sure what broke it in that version, but there's will be a new version of TDMorph coming out soon in December, compatible with latest builds.

**Comment by DarienBrito** [comment]
Solved in latest version
