### ISSUE TITLE
Blending preset menu is blank

### ISSUE THREAD

**Issue by vacuumn** [DarienBrito/TDMorph#183]
- TDMorph 3.0 Beta
- TD 2022.32660
- Windows 11

When clicking on either Preset A or Preset B little black rectangle appears instead of menu with existing presets. See screenshot:

![Screenshot 2023-05-18 210723](https://github.com/DarienBrito/TDMorph/assets/1943043/292af873-8b1b-428d-97c7-d65677bb2f02)

It works in PresetManager thought

**Comment by DarienBrito** [comment]
Fixe in 3.1.0
