### ISSUE TITLE
Beat sync broken? 

### ISSUE THREAD

**Issue by vacuumn** [DarienBrito/TDMorph#184]
- TDMorph 3.0 Beta
- TD 2022.32660
- Windows 11

When using beat sync in Expert mode, no matter what I enter in Bar/Beat/Sixteenth modes, it will still use hz from Manual/Internal modes.

In addition, beat sync seems to work on Scene Launcher, but changing value of Beats/Bars dosnt affects actual sync time.

**Comment by DarienBrito** [comment]
Oh yes, I didn't put too much attention on beat syncing. Will fix.

**Comment by DarienBrito** [comment]
This is fixed in upcoming 3.1.0 version
