### ISSUE TITLE
PresetAnimator is not creating Animation

### ISSUE THREAD

**Issue by vacuumn** [DarienBrito/TDMorph#185]
- TDMorph 3.0 Beta
- TD 2022.32660
- Windows 11

When pressing "Animation" on PresetManager, PresetAnimator being created but "There is no PresetManager given as a source error occurs". The PresetManager is being set correctly on PresetAnimator. Further Animation creation via PresetAnimator also gives the same error.

![Screenshot 2023-05-19 083313](https://github.com/DarienBrito/TDMorph/assets/1943043/5222d9d4-cee0-4701-8769-ab700fc207a2)

**Comment by DarienBrito** [comment]
I've been doubting whether to keep this one or not. Do you think this is a handy feature to have in general?

**Comment by vacuumn** [comment]
> I've been doubting whether to keep this one or not. Do you think this is a handy feature to have in general?

As most of people are using TD in realtime, the keyframing functionality frankly sucks.
I am all in for removing it completely, unless there are users who think otherwise.

**Comment by DarienBrito** [comment]
Alright, will consider it!

**Comment by DarienBrito** [comment]
Is fixed and will be kept in latest upcoming release (3.1.0)
