### ISSUE TITLE
Settings Error

### ISSUE THREAD

**Issue by OSC-Entity** [DarienBrito/TDMorph#187]
Off the bat, incredible work on this Darien.  I just started using TDMorph and it appears before I do anything else when attempting to click on the settings wheel I get an error. See attached screengrabs. Thank you!

<img width="416" alt="Screenshot 2023-06-14 at 6 32 25 PM" src="https://github.com/DarienBrito/TDMorph/assets/85541322/d5917b96-eca4-46a9-8e24-d69012da4a45">

<img width="1840" alt="Screenshot 2023-06-14 at 6 32 54 PM" src="https://github.com/DarienBrito/TDMorph/assets/85541322/8d75ba66-8d30-419e-b5a9-c394775051c7">

<img width="1840" alt="Screenshot 2023-06-14 at 6 32 52 PM" src="https://github.com/DarienBrito/TDMorph/assets/85541322/3f4666db-705d-4062-85ba-33f85bda8aa9">

TDMorph 3.0
TouchDesigner 2022.33600
Mac OSX Ventura 13.4

**Comment by DarienBrito** [comment]
Hi there. Thank you and good catch! There's a wrong reference to the master module that I must have missed while updating stuff. You can fix it for now like this: 
![Screenshot 2023-06-21 155017](https://github.com/DarienBrito/TDMorph/assets/5923038/b7e8bb67-5f4a-45d8-9efe-37d6ac79f3cb)

The expression should be:
`parent.TDMorphModule.op('Lib/ParPopup').Open(parent.TDMorphModule, 'Parameter Morpher Settings',"*")`

I will fix it in official release

**Comment by MattiaDiomedi** [comment]
Hi Darien, thanks for this great tool, just start to follow the tut, i get similar error when trying to open the container setting.
I'm using TD morph 3.0
Touchdesigner 2022.33910
Windows 11
![TD_Morp_SettingError](https://github.com/DarienBrito/TDMorph/assets/22443942/dbe50340-fef0-43f7-9e3e-1b2bea09e09a)

**Comment by DarienBrito** [comment]
This has been fixed in latest upcoming release (3.1.0) stay tuned on the repo :)
