### ISSUE TITLE
SceneLauncher - Delay is not editable

### ISSUE THREAD

**Issue by vacuumn** [DarienBrito/TDMorph#188]
TDMorph 3.0 Beta
TD 2022.32660
Windows 11

In the SceneLauncher all the columns are editable except Delay.

**Comment by vacuumn** [comment]
Can set the delay in `SceneLauncher/listScenes/Scenes` DAT, but rearranging scene will set everything back to 0

**Comment by DarienBrito** [comment]
This has been fixed in TDMorph 3.1.0 (coming out very soon, please keep an eye on the repo)
