### ISSUE TITLE
ParamterMorpher - Adding(+) new preset buttons error

### ISSUE THREAD

**Issue by vacuumn** [DarienBrito/TDMorph#189]
TDMorph 3.0 Beta
TD 2022.32660
Windows 11

When adding new presets using + button, they are added but their Container COMPs (/Container1/PanelContent/ElementsContainer/Presets/PresetButtons/Preset*) have error for **Enable** param:
`AttributeError: td.Shortcut  has not attribute 'KeysMapper"`

![Screenshot 2023-06-22 090935](https://github.com/DarienBrito/TDMorph/assets/1943043/4209f46a-5001-495a-a964-7ef576d65e67)

**Comment by DarienBrito** [comment]
Ah! Yes, I removed completely iOPs and forgot to clear those!

**Comment by DarienBrito** [comment]
Thanks so much for all the reports. Next release will com up much cleaner because of your reviews! :)

**Comment by vacuumn** [comment]
> Thanks so much for all the reports. Keep them coming. Next release will end up much cleaner because of your reviews! :)

Awesome! 
Thanks for the work, I'd like to see v3 without major bugs so that people could use it and enjoy advance morphing.  

Now I am working on music video and it is great to have beat sync, but hard to build scenes sequence without delays(found workaround) and more available presets.

**Comment by DarienBrito** [comment]
This is fixed in Beta 0.2, coming out in about one week,
