### ISSUE TITLE
Scaling GUI size causes unresponsiveness

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#19]
by jblanteigne:

I found a minor bug. Depending on the scaling and GUI size, if a dropdown menu ends up overlapping the top bar (easier to reproduce with interpolation because it’s long) it becomes impossible to click the first value which is over the top bar. The quick fix is to resize the GUI. this is minor.

**Comment by jblanteigne** [comment]
I created a bug report about this last week and instantly closed it because I am no longer able to reproduce it. It's also more about TouchDesigner's way of dealing with GUI scale, zoom in/zoom out and the size of drop down menus depending on how zoomed in or out you are in the GUI.

**Comment by DarienBrito** [comment]
I'll have a look at this. Did not really play too much myself with resizing the UI, so maybe there's some benefit to pay careful attention to what happens when one messes around with it

**Comment by DarienBrito** [comment]
Cannot reproduce. If something must be a TD bug somewhere.
