### ISSUE TITLE
TD Morph 3 - initial clock speed defaults to 1

### ISSUE THREAD

**Issue by jibberish666** [DarienBrito/TDMorph#192]
Hi

Is there any way to change the default value for the global speed setting?

When I save a project with TD Morph 3.0 any changes I make to the global morph speed get lost and reset back to value of 1.  I'd really like to default this to 0.2. 

Highlighted in the link below

Any help much appreciated.

![Alt text](https://i.imgur.com/ZV2ewDi.jpg)

**Comment by Garru-j** [comment]
Following this thread

**Comment by DarienBrito** [comment]
This is fixed in Beta 0.2, you can expect it to come out in one week time :)

**Comment by jibberish666** [comment]
Oh wow - looking forward to this.  Thanks so much :-)
