### ISSUE TITLE
TD Restart Issue: Loss of All Parameter Connections

### ISSUE THREAD

**Issue by verflixt** [DarienBrito/TDMorph#193]
First of all, TD Morph is one of the best breakthroughs in the TouchDesigner realm. Sadly, it seems that on Mac Silicon, it doesn't really want to work. I encountered an issue where, when I save a project with TD Morph 3 inside and reopen it, all my parameters that I connected to the parameter morpher are lost. Am I forgetting a step, or is it a bug?

**Comment by DarienBrito** [comment]
Latest TD versions caused plenty of problems with cloning, which TDMorph heavily relies on. This is fixed in version 3.1.0 (coming out very soon)
