### ISSUE TITLE
M3 Mac, TD crashes upon SceneLauncher import

### ISSUE THREAD

**Issue by foong** [DarienBrito/TDMorph#194]
Hey Darien, working on a M3 mac Sonoma 14.3 and TD crashes every time SceneLauncher is imported.

**Comment by DarienBrito** [comment]
Thanks for the report! This will be fixed in upcoming new version. Almost there... fixing some minor details and will upload. Stay tuned :)

**Comment by DarienBrito** [comment]
Hi Foong, I believe the issue is solved now. Could you try with the lates version on this repository?

**Comment by foong** [comment]
Okay, it's working now thanks! Will test out other features as well.
