### ISSUE TITLE
[3.1.0a] Blank fields in Path Editor after dragging an OP onto it (Mac OS)

### ISSUE THREAD

**Issue by rosofo** [DarienBrito/TDMorph#195]
https://github.com/DarienBrito/TDMorph/assets/50497130/7998da73-80b4-4f95-9c4a-30c9bffc9edb

[presetmanager_blank_rows_bug.toe.zip](https://github.com/user-attachments/files/15710933/presetmanager_blank_rows_bug.toe.zip)

## Steps to reproduce

1. Start a blank file
2. Drag in PresetManager
3. Add an OP
4. Open the path editor
5. Drag the OP in

## Extra details

- Field to the right appears editable but nothing happens if you type in it
- Same version works fine on my windows machine
- No errors in the python console
- The row seems to be captured properly internally:
   
   ![image](https://github.com/DarienBrito/TDMorph/assets/50497130/32371abc-bfb7-4bc9-81cd-1c6b2eff0789)

**Comment by rosofo** [comment]
Looks like the font isn't present on my system, switching it to another fixed the issue

**Comment by DarienBrito** [comment]
Oh yes, I see. I might need to choose a universal font to prevent this from happening across systems, or a switch to alter on system detection. Will add to "to do"

**Comment by DarienBrito** [comment]
Fixed. By default now fonts are Verdana and Material Design Icons. Tested on latest build on Windows and Mac.
