### ISSUE TITLE
Perhaps interpolation curve takes too much space?

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#23]
by jblanteigne:

This is minor. Because the red graph displaying the curve is only there to help us visualize the interpolation, I’d make it a bit smaller. Also I experimented with a “preview curve” pulse button that launches a demo transition where we can follow a cross made of a horizontal and a vertical line on the graph which follows the time and value axis to cross at the curve. (Sorry I find this hard to explain) It helps me associate this curve with the current transition length. Of course this animation only cooks when you pulse the preview. I find it fun but it’s really not that necessary.

Also, this is just my opinion but having control over the interpolation curve is a lot of parameters for not that much impact on the final result. I stick to a toggle between linear and “smooth” and I’ve been happy with this. For example, I find there is much more value in having a different interpolation time for each parameter and preset.

**Comment by DarienBrito** [comment]
1. Agreed on spacing. This will soon chang and new options will be added.
1. Will think about visualizing the change over the curve. Not sure if at all functional 
1. Disagree on fine tuning of curve, this can be very handy in non-linear use, two curves are definitely not enough. Will keep this unchanged

**Comment by jblanteigne** [comment]
reply to 2. I agree. I made this for fun but it's really unnecessary.
reply to 3. Makes sense. I don't think removing this potential will help in anyway and you implemented it really well. (individual curve per parameter!!) It's just my personal preference.

**Comment by DarienBrito** [comment]
1. Decided to remove indeed fine controls in favour of  universality,
2. Now viewer is done with a shader and takes minimum space
