### ISSUE TITLE
Add a "sequence" mode for stored presets (stack them so a timeline behaviour can be obtained)

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#24]
by jblanteigne:

Sequence Mode. I use this a lot. It’s useful if you can organize your presets quickly (renaming them, changing their order) because once you have many presets, the sequence mode will rarely output what you want. I control my sequence mode a bit differently. I export all the data in a single CHOP (one channel per parameter, a bunch of samples to recreate the interpolation between each values) and I “read” this sequence with a lookup chop. I would love to see this implemented in your tool. I think this feature is what makes the bridge between the morph workflow and the keyframe workflow. You can always convert to a more timeline style even if most of the work was done with the freedom of jumping between any presets and random values in a non linear way.

**Comment by jblanteigne** [comment]
Quick note on how I achieved this to retain the correct interpolation between each presets and without using the AnimationCOMP. ShiftCHOP can offset each preset's start position so when they are merged together with an InterpolateCHOP they all appear at their correct time frame. A filterCHOP can quickly smooth them.

That said, maybe an "Export to new AnimationCOMP" button could be useful.

**Comment by DarienBrito** [comment]
Something like this would be useful indeed. The approach I would take with is to use the animation COMP. That is simply a set of tables, which is very easy to write from TDMorph. This would allow for that "Timeline" approach to compose. I imagine now an in-between step where it would be possible re-order the presets people want. Could you elaborate a bit more on how do you see this working and why it would be useful?

**Comment by jblanteigne** [comment]
I use it for non real-time project. The main advantage of the timeline is that you no longer depend on triggering the interpolation, this lets you scroll in your animation. Of course I could do it all in the animationCOMP but I find it buggy and hard to edit properly. I want to avoid the keyframe approach as much as I can. A tool like TDMorph can let you play your scene in real time, try things out, change in which order each moment happens, how fast they happen. And I can still convert my project to a scrollable timeline at the end. In my opinion, any kind of "sequence" mode requires some preset management feature. It would be a pain to insert a new preset between 2 old one if you can't re-order them however. (I'm referring to issue #18 here) That said, I understand your point from issue #18.

**Comment by DarienBrito** [comment]
Ah I see. Nice. I think I will make a new component called "PresetsTuner" or something like hat, where all created presets are stacked and that allows numerous editing possibilites for presets to customize them in further detail, such as changing their timing, adding delays, creating logic rules, re-ordering and so on. From there one can generate a "Stream", which is possible to scroll thru and export as a waveform as well. I perhaps will in addition to that add the possibility of outputting an animation COMP to, because many people feel comfortable working with that as well. I'm closing this one and creating two new separate issues.
