### ISSUE TITLE
An option to auto save changes to current preset before switching to 

### ISSUE THREAD

**Issue by jblanteigne** [DarienBrito/TDMorph#25]
A quality of life / workflow feature.

Auto save each changes done to a preset as soon as you change preset to quickly edit all your presets one after the other without having to save them.

In the same frame of mine, adding a new preset could copy the current values to the newly created preset.

**Comment by DarienBrito** [comment]
Won't be doing this one. The philosophy with the tool is: every change of state has to be done explicitly. There will be no implicit functionality because that is not transparent nor general
