### ISSUE TITLE
Seperate "random" ranges

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#26]
Certain parameters like Camera Transformation might have a range you need access to that is wildly outside of the range that would be useful for a random or morphed value. Perhaps under the inspector for an individual parameter one could clamp different values for generated parameters.

A resolume style range slider for parameters that allows for easy lookup could be a great feature

**Comment by DarienBrito** [comment]
Ah yes, this is part of the plan already. In next iterations you will be able to not only create sliders but also range sliders :)
