### ISSUE TITLE
Next and Previous preset buttons

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#27]
The sequence mode is cool, but the way I find myself using this system is to store looks that look good and trigger them live at a big musical moment. I would love the ability to just have a next and previous preview button to easily bump through stored looks. A random and morph button that only goes through preset looks could be a nice way to mix it up while only hitting approved values

**Comment by DarienBrito** [comment]
Ah, I think I know what you mean... well, there is a very powerful object inside TDMorph called "PresetManager" that can do this (is UI-less though) but I have not made a tutorial for it yet. I will create documentation for it soon for the first week of February perhaps. This object can open a whole world of possibilities because its meant as a general global preset storage system. More on it soon.

**Comment by DarienBrito** [comment]
Note to self: do video tutorial.

**Comment by drmbt** [comment]
Awesome. I would love to know more about how you imagine the optimized workflow to look like. For example, if i have a scene that has a TDMorph in it, with a sliders container for camera, another for color, and a third for materials, should that live in the Tox, or at a top level? Should there be multiple instances of TDMorph in seperate Toxes, or should that exist in a separate UI container? Should the UI be selecting panels that live inside individual scenes?

**Comment by DarienBrito** [comment]
The general idea is that there should be only 1 instance of TDMorph at the top level. I see it as a global controler and not a scene based one. This is how I use it. However, this depends on how people build their networks, so there's nothing wrong with having different instances if you need them. I made sure that TDMorph is as efficient as possible, so nothing cooks unless you perform a transformation.

**Comment by DarienBrito** [comment]
I will not do this exactly what this enhancement describes because at the core of this suggestion there's another underlying concept which is the real enhancement. I am closing this issue and opening a new one with a different description.
