### ISSUE TITLE
PresetComposer: a preset chaining suite of tools 

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#36]
To further customize in details presets. This will allow various fine-grained controls to cue presets. See #28, #24 #39, #18, #29   

Essentially something like the clip launcher in Ableton, but on steroids.

**Comment by jblanteigne** [comment]
In reference to issue #24: 

> Ah I see. Nice. I think I will make a new component called "PresetsTuner" or something like hat, where all created presets are stacked and that allows numerous editing possibilites for presets to customize them in further detail, such as changing their timing, adding delays, creating logic rules, re-ordering and so on.

You mentioned this node is meant to manage presets. So could this be part of the existing Preset Manager node?

As far as I understand, the Preset Manager node is a secondary GUI meant to send the same commands that can be sent to TDMorph as described in the "No UI, I just want to code!" part of your guide. I think re-ordering or sorting presets should be available through those commands.

I'm not sure what you mean by preset timing, delays and logic rules. Is it something similar to my warpTo feature suggestion? #28 ?

I think this type of preset launch system happens 1 layer above preset management. After working with this kind of tool for years now, I see two different workflows forming two layers. The first is exactly what can be found in TDMorph, you organize data in presets to create sweet spots, arrangements of parameters that work together. This is the data layer where you enter and sort all the values. The second layer is how you build a structure with all this data. How it's organized to create a timeline or a performance. Maybe all the features related to how and when the presets are launched could be found in a Preset Launcher node.

**Comment by DarienBrito** [comment]
> You mentioned this node is meant to manage presets. So could this be part of the existing Preset Manager node? As far as I understand, the Preset Manager node is a secondary GUI meant to send the same commands that can be sent to TDMorph as described in the "No UI, I just want to code!" part of your guide. I think re-ordering or sorting presets should be available through those commands.

Maybe. Need to do some testing to see where is the best place to implement this suite.

> I'm not sure what you mean by preset timing, delays and logic rules. Is it something similar to my warpTo feature suggestion? #28 ?

This is based on something like the preset possibilities of the Control Forge CV controller for modular synths, which allows for all sort of neat things.

**Comment by DarienBrito** [comment]
Began the process. This will be a separate component, special for fine editing of presets including many cool features. Its gonna be quite handy!

- [ ] Implement local referencing of Curves
- [ ] Implement draggable rows
- [ ] Implement editable fields
- [ ] Implement cues
- [ ] Add delay options
- [ ] Add logic options (alla Control Forge)

**Comment by DarienBrito** [comment]
Really happy with how things are turning! Preset composer is getting very powerful... here a sneak peak @johannbl @drmbt

![Capture](https://user-images.githubusercontent.com/5923038/80869211-69be7680-8c9f-11ea-89a1-79e61b2cb5a6.PNG)

**Comment by johannbl** [comment]
Awesome! looks just like the tool I was using. Can't wait to try it out!

**Comment by drmbt** [comment]
refreshing daily, anxiously awaiting that sweet sweet 2.0

**Comment by DarienBrito** [comment]
> refreshing daily, anxiously awaiting that sweet sweet 2.0

Should not take too much longer :) I'm hoping to complete it all by the end of this month (May 2020)

**Comment by DarienBrito** [comment]
- [ ] Add signals outputs
- [ ] Add sequencial mode

**Comment by johannbl** [comment]
Hi Darien,

Based on the screenshot alone I can share my experience creating long sequences with this type of tool. I was also using a transition length per cue and after a while I realized that I often needed to know the total length of my sequence. Not as a parameter but just as feedback to better understand what's going on. I'm wondering what you think of this.

Also. off topic but I remember you mentioned a way to export to this to an AnimationCOMP? is that coming for 2.0? Is it possible to import/export those settings to a xml file as well?

**Comment by DarienBrito** [comment]
Hi @johannbl,

Thanks for your message. I see, you mean you would like to have somewhere an indication of the total duration of all the lenghts + delays combined? 

Yes, the presets to animation conversion is already implemented and working nicely. It will be definitely included in TDMorph 2.0 :) Incidentally, there there's an indication of total duration, like you suggest for the PresetComposer. I have not added a JSON or XML exporter for the PresetComposer nor the AnimationCOMP, but I can surely add that to the mix ;)

**Comment by DarienBrito** [comment]
- [ ] Save colors, delays and actions in presets

**Comment by DarienBrito** [comment]
Preset Composer is complete!

![Capture](https://user-images.githubusercontent.com/5923038/81342561-b8ab4800-90b3-11ea-82fa-379b8cdbc45d.PNG)
