### ISSUE TITLE
Renaming TDmorph causes error

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#42]
Looks like it breaks some connection to Recall1 outputs deep inside the Library. Seems to be fixed on create, so renaming the TDmorph container, cutting and pasting it back in place reconnects things as it should

**Comment by DarienBrito** [comment]
Aha! I see. Strange one... maybe I'll use selects instead of outs to avoid this kind of thing.

**Comment by DarienBrito** [comment]
Fixed. Download V1.1.1
