### ISSUE TITLE
When reimporting from Json, parameters are shuffled alphabetically

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#43]
If i export and then re-import a json, the parameters are imported alphabetically into the slider array, but the sliders remember their preset information by position. This bug can easily be reproduced by dropping a constant into TDmorph, setting R G B as three presets, and then exporting and importing into a clean TDmorph instance. The colors come in as BGR, but the values are recalled based on the parameter position

**Comment by DarienBrito** [comment]
Oh I know what caused this. Will fix asap.

**Comment by DarienBrito** [comment]
Fixed, download V1.1.1
