### ISSUE TITLE
feature request: Interpolation mode pulse on end

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#46]
I know you can do this with callbacks, but it would be nice if in the TDmorph GUI there was an interpolation mode that jumped to the change at the end of the timer. This would be especially nice for timing hard cuts to be exactly where you want them in the animation curve.

**Comment by jblanteigne** [comment]
In a similar train of thought? How about a delay parameter. It would be very interesting to delay different parameters differently to create a "layered" transition.

**Comment by drmbt** [comment]
Realistically, that would just be an offset on when the envelope kicks in. This would solve my ask, with pulse or square that has an offset

**Comment by DarienBrito** [comment]
Not sure I understand the request, could you elaborate a bit more? Maybe with an image of sorts? :P

**Comment by jblanteigne** [comment]
It's like an inverted pulse.
[https://i.imgur.com/b7XNyvb.png](url)

In other words, there is no interpolation, the values are loaded instantly, but after a delay. The length of the delay is equivalent to the morph time. Hence why I suggested a delay parameter.

**Comment by drmbt** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/6729692/75825735-94598500-5d6b-11ea-8c51-dc52ae7b5dd6.png)

I meant something like this, just having a pulse at the end of your timer or at the beginning, so that one could offset a change at the end of 3 seconds for example, instead of immediately. I think jblanteigne is asking for a delay before the curve, some sort of pretimer before the transition occurs so that you could stagger/offset interpolations between parameters

**Comment by jblanteigne** [comment]
Exactly. I understand the two requests are different but yours is probably easier to implement.

**Comment by DarienBrito** [comment]
@drmbt Alright, so basically an interpolation curve that is really a square wave which you can set to change to next state at the beggining or end. Correct? 

@jblanteigne Sure! I like the idea of adding delays at will for the morphings. Will be done in next major update V2.0, not in next minor (V1.1.2)

**Comment by DarienBrito** [comment]
This is done in V2.0.0 in the form of a stepper with a movable offset. This covers both requests at once.
