### ISSUE TITLE
RFA: Right click par to return to saved value of most recently triggered preset

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#49]
A Resolume or Ableton style way of recalling either the default value recorded with the paramete, or the value from the most recently triggered preset would be very helpful. Kind of how now retriggering the preset brings everything back home, being able to do that per parameter would be clutch

**Comment by DarienBrito** [comment]
You mean some mechanism to reset to the value that was found on a given parameter on slider creation?

**Comment by drmbt** [comment]
preferably the value from the most recently recalled preset, but the default value would be a second choice if its easier

**Comment by DarienBrito** [comment]
I will do the value found on default, because to get the most recently recalled preset, well, one simply clicks on that preset. There's a new mechanism in V2.0 to jump to a preset without interpolation, which will make this even more clear.

**Comment by DarienBrito** [comment]
Implemented in V2.0. This will affect also the range of the slider, since original value can be outside the bounds of altered range. Shift left-click over slider name to reset slider to original values.

**Comment by drmbt** [comment]
i would argue that recalling a preset will recall the value of all your sliders, not just one, so there is still a reason why a rselect or shift click or whatever to return to the saved value makes sense, but I'm perfectly happy with recalling the default. Is there a reason you prefer shift lselect to rselect for this?

**Comment by DarienBrito** [comment]
There's a whole new set of functionality with shift and ctrl + clicking combinations. In new version, shift+left click resets to default value for slider and shift+right click allows you to rename the slider (instead of current double clicking on label). Main reason is efficiency, since in this way no CHOPS whatsoever are used, with reduces CPU usage to minimum, and makes the code much cleaner.

**Comment by drmbt** [comment]
That makes sense. Its an extra keystroke, but i suppose its better ultimately for my use case anyhow, as I'm trying to build most of my GUIs to be touchscreen friendly, and a modifier key is probably better then trying to do a two finger tap
