### ISSUE TITLE
clicking on export in GUI doesnt generate tables

### ISSUE THREAD

**Issue by perottosson** [DarienBrito/TDMorph#50]
clicking on export in GUI doesnt generate tables but works as it should in the presetmanager

**Comment by DarienBrito** [comment]
It seems to be working fine here. Are you sure you had presets saved?

**Comment by DarienBrito** [comment]
I've tried to replicate this but it works fine. Probably you did not have presets stored and hence there was not table being created ;) If you still find issues please reopen.
