### ISSUE TITLE
Icon resolution

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#53]
This is a super teeny tiny nitpicky low priority thing, but also a super quick fix. I've been riffing on customizing the GUI a bit, and for situations in which I might want, for whatever reason, a larger version of any of your buttons, the low res icons show up pretty blurry. 

I'm hoping you could set input smoothness to nearest pixel on a few of your icons like the Dice i.e. so that they will display nicely at a larger size

**Comment by DarienBrito** [comment]
Ah ok. I was thinking to change a bit the file structure in order not to rely on locking things, perhaps I'll do this when that change is made.

**Comment by DarienBrito** [comment]
All icons changed since re-design in V2.0.0. This request is no longer valid.
