### ISSUE TITLE
High level syncing for LFO's

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#55]
I'd imagine your pattern implementation will make this unnecessary, but it would be nice to sync that LFO to a tempo being fed to the top level like the midi source operator. Ableton Link mode would allow it to directly sync with any other DAW or plugin if you pointed a link chop at it, would make it super great for talking to resolume or ableton

**Comment by DarienBrito** [comment]
For now there is a new Hard Sync mechanism that allows to reset all LFO's in a container so that they start in sync. I am not familiar with AbletonLink in TD so I don't know how that works, feel free to suggest something later if there's need for it in the form of a patch :)  I will implement this with a "Transport" input for TDMorph... wip...

**Comment by DarienBrito** [comment]
Fuck it, doing it right now...its actually pretty easy. Creating now a TransportManager to handle various types of syncing, this will be capable to handle both TD's Beat CHOP and the AbletonLink CHOP seamlessly.

**Comment by DarienBrito** [comment]
Completed. Integration with Master clocks via the Beat and Ableton Link Chops implemented, with additional controls that allow for syncing either on each beat, on specific beat or on specific bar. Many more possibilities are now open and easy to add since I have created a robust framework for external syncing wit LFO's and Patterns. Will develop further as V2.0 matures.

**Comment by drmbt** [comment]
Awesome! does it have to be a beat/link chop, or can you just feed it a tempo via a float? I feel like the ideal scenario is an input op like you've already done for midi and osc, so that TDMorph doesn't care where its coming from, just needs a floating point tempo value

**Comment by DarienBrito** [comment]
That's exactly the case. It works in the same way as MIDI or OSC input, its an additional input called "Transport", simply pass a CHOP to it and you are done ;)

It has to be a beat/link, because a floating tempo value does not contain enough beat information by itself. I am not calculating beats or subdivisions inside, I'm grabbing already generated tempo information, which should be the case since there are already dedicated operators for that (namely link and beat)
