### ISSUE TITLE
v1.1.2 custom parameters are assuming a strange value on drop

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#56]
This isn't an issue in 1.1, but it seems that custom parameters are set with a value changed to 60.39% of their maximum value when dropped and bound. a very specific and odd behavior...

**Comment by drmbt** [comment]
you can recreate by creating a base with a few custom parameters with odd max values, setting them randomly, and then adding them to a TDmorph slider container. You'll see that they are set to 60.393 if your maximum value is 100 in this case

**Comment by DarienBrito** [comment]
mmm... this must be the re-ranging... will have a look.

**Comment by DarienBrito** [comment]
Note to self: write val after ranging occurs.

**Comment by DarienBrito** [comment]
Fixed in 1.1.3
