### ISSUE TITLE
Enhancement: a quick "check" option for presets that overrides the stored time 

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#57]
This suggestion is most useful when working with slower transition time. Imagine the following case:

Each of my stored presets have unique transition times ranging from 5 seconds to 60 seconds.
I want to quickly visualize, adjust or verify stored values without losing any stored transition time values that previously saved along each stored presets.

There could be a switch with its own float value that lets you override the time parameter to quickly test my transitions with a static duration of 1.0s.

**Comment by DarienBrito** [comment]
Ah, that's interesting! I can definitely see how this might be useful. Will be included in next major release 👍

**Comment by DarienBrito** [comment]
Done in V2.0.0. ctrl+left click jumps to selected preset instantly, disregard of stored time.
