### ISSUE TITLE
V1.1.2 - Bug - Global mode transition time won't display value stored with presets

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#58]
Basically, the global time parameter shown at the top right only displays the last value input by the user even when you recall a preset which was saved with a specific transition time. Because of this, it's very hard to keep track of how long each transition is.

**Comment by DarienBrito** [comment]
Yes, this was changed because there were issues introduced when updating the value, because of the way this was done. Will be revised later.

**Comment by DarienBrito** [comment]
This is not a bug but a feature under revision, will be solved in upcoming major release, after major UI redesign.

**Comment by DarienBrito** [comment]
Resolved by accident 😄! Changing the design of pulling data  from timer has the nice side-effect that solves conflicts in setting-fetching vals from the MetaControls base. 

Fixed in V1.1.3
