### ISSUE TITLE
V1.1.2 Bug - SetUIStorePreset(int) and SetPreset(int) are not using the same starting index

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#61]
I thought there was a bug with the StorePreset method but it's not as bad as I thought, here's the issue.

I am currently loading preset 1 using SetPreset(0). However, in order to store preset 1, I have to send StorePreset(1)

**Comment by DarienBrito** [comment]
Ah yes, this is open for debate. I decided to keep the setting of presets according to the labels (since they start from 0, not 1) because I thought that would make more sense for people. Although yeah, most people using the method may expect starting from 0. What do you think?

**Comment by jblanteigne** [comment]
I'm not sure what I personally prefer but I have an argument for starting from 1. 
When using a chopexec node and momentary buttons, it's handy to use the offToOn function with values over zero being the preset index. That said, a simple math chop can format data one way or another.

**Comment by DarienBrito** [comment]
Fixed V 1.1.3

All high level UI methods begin now from 1. These are:

- SetUISetPreset
- SetUIStorePreset
- SetUIUnstorePreset
- GetSlider

If a number below 0 is sent, TDmorph prints a warning to the console

**Comment by johannbl** [comment]
At the moment, PresetManager's preset index starts at 0. Shouldn't they share the same starting index too?

**Comment by DarienBrito** [comment]
There's a difference between the high level UI commands SetUI[something] (which all start from 1) and the Preset Manager, which implements core functionality and stores data in a different data structure. This data always start from zero. High level commands are user-friendly while low level commands should be programmatically consistent.
