### ISSUE TITLE
Add option to cancel morphing

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#64]
When doing a long morphing, sometimes is handy to be able to cancel it.

**Comment by johannbl** [comment]
What do you think of this behavior:

- During an interpolation towards preset 1, clicking preset 1 again pauses the interpolation.
- Clicking on any preset button will launch a transition towards this preset, including pressing preset 1 again.

**Comment by DarienBrito** [comment]
That may bot be a good idea as it is a bit confusing and overlaps behaviours for each button, which programming-wise is not very good design.

I think I will implement a form of a pause/stop mechanism, both for global and local behaviours.

**Comment by DarienBrito** [comment]
Done in V2.0
1. Stop button as meta control for containers
1. Pause/play button as meta control for containers.
