### ISSUE TITLE
Values defined in Range Slider parameter are not clamped correctly when MIDI is assigned

### ISSUE THREAD

**Issue by aaapoc** [DarienBrito/TDMorph#66]
Hello,

Firstly, just want to say thank you for the amazing tool!

As the title says, the values defined in the 'Range' min and max fields are not clamping correctly when there is MIDI assigned to the parameter. 

For example, a range of 10 (min) and 5000 (max) is outputting ~400 (min) and 196,466 (max). 

Another example: a range of 1 to 4.5 is outputting ~1.02 to 1.12...

Could you kindly advise? Hope the screenshot clarifies [things](https://i.imgur.com/gcYBIzY.png)

Thank you,

**Comment by DarienBrito** [comment]
Hello there! Will have a look later in the eve. Is this only when mapping MIDI or does it happen in other cases? Just rolled out a new version today (V1.1.3), so there might be some broken things here and there.

**Comment by DarienBrito** [comment]
Ah but wait... are the values you are feeding via MIDI scaled already? TDMorph expects MIDI values in the range from 0 to 127, so you don't need to pre-scale. Maybe this is what is happening?

**Comment by aaapoc** [comment]
Hi Darien. Thank you for the quick response. Your suggestion to not scale MIDI values prior to plugging them into TDMorph is working now. Thanks so much!

**Comment by DarienBrito** [comment]
Great!
