### ISSUE TITLE
System optimization and redesign

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#68]
- [x] Change presets push for pull system
- [x] Upgrade icons and compartmentalization to Roy's
- [x] Test the patterns suite
- [x] Implement the patterns UI

**Comment by johannbl** [comment]
I'm wondering what you think of this GUI change.

![TouchDesigner_CfUN5tOBVv](https://user-images.githubusercontent.com/10411890/78508143-9344ba80-7752-11ea-9ff7-527f7b66f90d.png)

**Comment by DarienBrito** [comment]
Thanks for the suggestion! The whole UI is changing quite dramatically... it is gonna be prettier and way more compact and intuitive. Roy Gerritsen (fellow TouchDesigner freak) had some great ideas for that and is helping me improving the UX design quite a bit. Major upgrades coming in the next months!

**Comment by DarienBrito** [comment]
New UI look (color is customizable):

![Capture](https://user-images.githubusercontent.com/5923038/79325390-64c49d80-7f11-11ea-9dc0-86cd100b96f7.PNG)

**Comment by DarienBrito** [comment]
Patterns implemented and working! The exact manner on which they should function remains to be seen. I have made a code oriented interface as a first experimental version.
