### ISSUE TITLE
Version 1.1.3 Sliders in UI Don't clamp 

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#69]
I'm not even sure if I'm mad at this, cause I could see scenario's where its nice to overdrive these values from the UI, and MIDI/OSC work as expected, but if you're not controlling it externally (maybe a touchscreen, or just a mouse), having the option to keep the faders clamped to your specified range is ideal

**Comment by DarienBrito** [comment]
Yes, there was an issue about this already but now I cannot find it, maybe I did not write it here in Github. This will be solved after the major UI re-design that is in process...

**Comment by DarienBrito** [comment]
This is fixed in version 1.1.4
