### ISSUE TITLE
Bug: Cannot store negative values

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#70]
When trying to set a parameter to a negative value, it initially sets it back to 0.0. But the 2nd time you try it, you can actually set a parameter to a negative value.

The actual issue here is that those values get clamped to 0.0 when stored so recalling the preset will recall a value of 0.0 for this parameter.

**Comment by DarienBrito** [comment]
Not following this one. Negative values seem to be working fine: 

![Capture](https://user-images.githubusercontent.com/5923038/78700990-8799f500-7906-11ea-9ac2-01a5141d3fc2.PNG)

Do note that if you are trying to do it in a non-custom parameter it may have this value clamped by default, so you cannot set it to negative no matter what. You can tell if its possible by re-ranging the parameter in TDMorph to -1 and 1 for example. If it allows it, then it means that the parameter supports negative values, if not then this cannot be changed.

**Comment by johannbl** [comment]
My bad. This is not a bug. I just assumed I could store values outside the specified range.
