### ISSUE TITLE
Local mode with stand alone PresetManager

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#74]
I'm using a PresetManager to control a camera position. I'm interested in controlling morph time in a different way by setting a camera movement speed that sets the morph time in seconds based on how far the recalled preset camera position is. So Local mode would work for creating this. I see it's possible to set a standalone PresetManager to "local" mode with .UIGlobalStatus(0) but as far as I understand, because the sliders don't exist, it's not possible to fully use the local mode with a standalone PresetManager, is that right?

**Comment by DarienBrito** [comment]
Yes, PresetManager local status does not exist. Local is only a UI mode, so you cannot do that in this way. I don't see though why you would need "local" behavior to do this?

**Comment by johannbl** [comment]
Global mode stores and load the morph time value with presets. In my case, morph time will be variable depending on the distance between origin and destination so I'd like to avoid conflict between storing/loading the wrong value and my own tool overwriting the morph time whenever I load something. Local Mode was a workaround for this as I would be able to change the slider morph time parameter without conflicting with stored time morph per preset.

**Comment by DarienBrito** [comment]
I see. This is something you cannot easily do with the PresetManager unfortunately. Local modes are only for containers and it is not trivial to expand this to a PresetManager. A specific module will have to be made that can handle this. I will leave this question open for later, maybe at some point I can look into it. Feel free to work on it and make a suggestion, like with the WarpTo idea you sent :)

**Comment by johannbl** [comment]
I feel like there's no way to cover every possible features for a tool like this, however, a suggestion I made before would help with what I'm trying to do here. It's also more versatile.

#57 Basically, a more global, global time that overrides everything.

**Comment by DarienBrito** [comment]
Mmm, issue #57 is going to be done in a different way, just as a quick-preview and not as a yet another global time controller. I will not add additional global, global controls, because that's really fringe use.  What you want to do is quite specific, so has to be done with a custom node, not with alterations or additions to the main program.

**Comment by johannbl** [comment]
Yeah I understand changing the time parameter to a "speed" parameter is quite fringe. I'm curious to see how #57 will be handled, it doesn't have to be a separate parameter, just a way to not automatically store and load the morph time with each preset.
