### ISSUE TITLE
Container method to get PresetManager is mispelt

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#75]
So I was following the tip you gave me previously and I found this at line 147 of "TDMorph/SlidersContainer1/PanelContent/SlidersContainer/extSlidersContainer"

```
	def GetPresetsManager(self):
		return op('PresetManager')
```

Shouldn't it be spelt GetPresetManager without the s?

**Comment by DarienBrito** [comment]
Good catch! Yes, to be 100% consistent should be GetPresetManager()

**Comment by DarienBrito** [comment]
Fixed in V2.0.0
