### ISSUE TITLE
V1.1.4 performance issue

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#77]
I've noticed some jittery transitions in the camera tool I'm working on. I noticed it because it was apparent in the results during a transition as opposed to a direct control of the parameters.

![TouchDesigner_9oUL9jkfN1](https://user-images.githubusercontent.com/10411890/79363124-8162d480-7f15-11ea-8e60-7c0d0006e44c.png)

This might not look like much but it can be seen. I'm using a PresetManager with the timer disconnected. (btw, I saw your enhancement about being able to override the timer in 2.0, thank you)

I was able to reproduce the bug in a clean project, even while TDMorph's GUI is "muted" and running TD in non-realtime. That said, the transition seems much cleaner in this situation so, TDMorph is not be the only culprit in my case and I will be optimizing my system as much as I can but I was surprised to find the issue when TD is running offline.

I also got really clean interpolations from a normal timer, even while TDMorph is running, so it's not my TD instance lagging.

I understand TDMorph is more than a Timer.. and I know many things are setup when values are loaded before the transition occurs but the jitter happens in the middle of the transition as well.

Here's the patch.
[TDMorph_PerformanceTest.zip](https://github.com/DarienBrito/TDMorph/files/4482574/TDMorph_PerformanceTest.zip)

edit: I think I'm overreacting a bit... I got very good results in my patch in perform mode, hiding everything. I think it's mostly TD GUI.

**Comment by DarienBrito** [comment]
Will have a look at it! Good to have some form of "benchmark" so I can further optimize V2.0.

V2.0 is already more performant and is warrantied not to cook at all when idle and, to use minimum resources when active. I'll see if your patch can show where to optimize it even more.

**Comment by DarienBrito** [comment]
After investigating this... I don't see jitters in between transitions on my machine while on editing mode and real-time enable. I only see tiny artifacts on start or very end, which is expected and unavoidable I am afraid, since there are a lot of internal things being written here and there that take time. 

These tiny jitters are for the most part negligible as far as I can see. Will close this issue and if something else along these lines shows up will be re-opened for V2.0
