### ISSUE TITLE
Optimize preset writing via CHOPS only

### ISSUE THREAD

**Issue by DarienBrito** [DarienBrito/TDMorph#83]

**Comment by DarienBrito** [comment]
As it turns out, at first glance DAT -> CHOPTO is faster than ScriptCHOP... More testing needed....

**Comment by johannbl** [comment]
Speaking of testing.. can we help?

**Comment by DarienBrito** [comment]
> Speaking of testing.. can we help?

Yes! I am almost there with the private beta of V2.0, I think will be ready this weekend. @johannbl, @drmbt You are in my testers list since the beginning, would be great if you can give it a first go! 😄

**Comment by DarienBrito** [comment]
Nope, definitely scripCHOP is faster than DAT -> CHOPTO (as intuitively assumed). Thing is that is not linear time, so scriptCHOP shines when many channels are written. In my test with 1000 channels, ScriptCHOP cooks at 0.0128 seconds, while DAT->CHOPTO at a crazy 5.699 seconds, thats a huge difference!

scriptCHOP is the way to go!

**Comment by DarienBrito** [comment]
Done. Preset writing and morphing should now be more efficient.

**Comment by drmbt** [comment]
Can't wait. I've been cooking a weird remix of 1.4 that I'll drop somewhere soon. maybe a lot of it is redundant, but I think you'll agree it has some interesting bits
