### ISSUE TITLE
Local Mode Recall Preset GUI animation broken

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#87]
A small one. Recall preset GUI buttons update (the progress bar that also serves as a focus indicator) is stuck when switching to local mode. Works fine after a launching a transition in global mode.

**Comment by DarienBrito** [comment]
Solved. The indication bar now moves to the right preset on click. It will not animate however, because in local mode times for each parameter can be different, so would not make sense to have a time indication that may not reflect all local changes.
