### ISSUE TITLE
Sync button doesn't update slider length param GUI

### ISSUE THREAD

**Issue by johannbl** [DarienBrito/TDMorph#89]
Sync button doesn't update the displayed per slider length parameter float box as it should leading to a case where displayed values and actual values aren't the same.

Also, does the sync button have a use when you're in global mode? If not, maybe the sync button could be hidden or grayed out?

**Comment by DarienBrito** [comment]
Solved. UI elements now update properly. And yes, it is mode-independent. In either mode it will change the local time values, this is handy ti revert to a unified time at any point if wanted.
