### ISSUE TITLE
Owner check for parent shortcuts

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#92]
I think we may have chatted about this back during 1.something, but it would be amazing if on creation of a new par, it checked to see if the owner has a parent shortcut associated with it, and if so referenced that instead of an absolute path. The binding manager makes it possible to manually go in and redirect the owner, which is super helpful, but this way you get the best of both worlds and a workflow for portability that is free, especially in the instance of packaging TDMorph into a tox that should just be drag and drop

**Comment by DarienBrito** [comment]
I totally see the appeal of this but it has to be done in the right way. Doing a manual check to see if a global or parent shortcut exists and prioritize that is not the best solution for this in my opinion.

I am waiting to talk with Markus about this because what I really want to do is to create a dynamic paths system that will automatically adjust the paths if the user moves the nodes somewhere else. This should be possible because TD does this already, but I have not found info yet on how to access that functionality.

**Comment by drmbt** [comment]
That still doesn't solve the problem of kicking out a tox containing a TDMorph instance and bringing it into another project. I feel like there's gotta be a way to get this for free, because TD does it already... if you reference a parameter from a parent container that has a Parent shortcut, it resolves to that. All I know is that finding a way to make it dependable across projects seems important. Binding manager should fix this, but if you check my other issue, it doesn't seem to be working as intended. Let me know if I'm missing something there, its definitely a way to get what I need, but an automated solution is obviously ideal

**Comment by DarienBrito** [comment]
Parent shortcuts may allow portability if the user is careful enough to name components consistently across projects, but that does not address the (bigger) issue of changing levels of parent/children and so on within a project. I first want to focus on that and only later see about cross-projects portability. There must be some simple method to achieve this but it is not in the official documentation AFAIK. I'll mail Markus soon about that.

**Comment by drmbt** [comment]
does 'Done' mean you found a  clever solution?

**Comment by DarienBrito** [comment]
Wooops, no, just put it in the wrong column. Not done yet, in progress.

**Comment by DarienBrito** [comment]
Will focus on this after first release. Structurally too big of a change to tackle at this point.
