### ISSUE TITLE
Updating BindingsTable from settings doesn't take

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#93]
If I drop a new TDMorph create noise1 and noise 2, and bind some parameters from noise 1, I should be able to change the owner to noise2 in the bindings pulse table and have it update its bindings. That table doesn't actually push those new values, and when pulsing the menu again, it reverts to its previous information

**Comment by DarienBrito** [comment]
Good one! As it turns out I totally forgot to link table change to Bindings re-generation. Now this is working properly.
