### ISSUE TITLE
Global Morphing Functionality

### ISSUE THREAD

**Issue by drmbt** [DarienBrito/TDMorph#95]
It seems that the StopGlobalMorphing command pops you back to where you were, and the PlayGlobalMorphing command freezes it, but it would be nice to stop it where it is and have the option to continue morphing from that point. You can't morph again if its frozen, and unfreezing it will continue the transformation without the ability to cancel the morph while leaving the parameters at their new point. 

Let me know if that makes sense...

**Comment by DarienBrito** [comment]
> It seems that the StopGlobalMorphing command pops you back to where you were, and the PlayGlobalMorphing command freezes it, but it would be nice to stop it where it is and have the option to continue morphing from that point.

PlayGlobalMorphing is a play/pause mechanism. It pauses morphing when enabled and re-activates it when disabled. Like playing/pausing a movie.

Stop takes you always to the previous saved state before attempting to morph, which is the most common behaviour one would want from a stop button.

> You can't morph again if its frozen, and unfreezing it will continue the transformation without the ability to cancel the morph while leaving the parameters at their new point.

If one ones to cancel the morph while leaving the parameters at the stopped point, one creates a new preset at the paused state, stops the morphing and goes to the new saved state, simple as that. This is what the intention is with playing/pausing/stopping.
